# Task: Study the various Recommendation Techniques for recommending movies 

Using movies.csv, ratings.csv datasets.

•Load movies.csv and ratings.csv dataset
•Merge both data frames on movieid
•Create User-Item Matrix (Hint: Use pandas pivot_table method with index = 'userId', 
columns = 'title', values = 'rating' )


In [ ]:
# !pip install scikit-surprise

In [35]:
import pandas as pd

In [36]:
movies = pd.read_csv('../../Datasets/movies.csv')
ratings = pd.read_csv('../../Datasets/ratings.csv')

In [37]:
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [38]:
ratings.describe()

userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [39]:
ratings.drop(['timestamp'], axis=1, inplace=True)

In [40]:
ratings.columns

Index(['userId', 'movieId', 'rating'], dtype='object')

# 2. Merge both data frames on movieid

In [41]:
df_combined = pd.merge(ratings, movies, on='movieId')
df_combined

userId  movieId  rating                           title  \
0            1        1     4.0                Toy Story (1995)   
1            1        3     4.0         Grumpier Old Men (1995)   
2            1        6     4.0                     Heat (1995)   
3            1       47     5.0     Seven (a.k.a. Se7en) (1995)   
4            1       50     5.0      Usual Suspects, The (1995)   
...        ...      ...     ...                             ...   
100831     610   166534     4.0                    Split (2017)   
100832     610   168248     5.0   John Wick: Chapter Two (2017)   
100833     610   168250     5.0                  Get Out (2017)   
100834     610   168252     5.0                    Logan (2017)   
100835     610   170875     3.0  The Fate of the Furious (2017)   

                                             genres  
0       Adventure|Animation|Children|Comedy|Fantasy  
1                                    Comedy|Romance  
2                             Action|Crime|Thriller  
3                                  Mystery|Thriller  
4                            Crime|Mystery|Thriller  
...                                             ...  
100831                        Drama|Horror|Thriller  
100832                        Action|Crime|Thriller  
100833                                       Horror  
100834                                Action|Sci-Fi  
100835                  Action|Crime|Drama|Thriller  

[100836 rows x 5 columns]

In [42]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   userId   100836 non-null  int64  
 1   movieId  100836 non-null  int64  
 2   rating   100836 non-null  float64
 3   title    100836 non-null  object 
 4   genres   100836 non-null  object 
dtypes: float64(1), int64(2), object(2)
memory usage: 3.8+ MB


In [43]:
ratings_matrix = df_combined.pivot_table(index='userId', columns='title',values='rating')
ratings_matrix

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              NaN                                      NaN   
2              NaN                                      NaN   
3              NaN                                      NaN   
4              NaN                                      NaN   
5              NaN                                      NaN   
...            ...                                      ...   
606            NaN                                      NaN   
607            NaN                                      NaN   
608            NaN                                      NaN   
609            NaN                                      NaN   
610            4.0                                      NaN   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                          NaN                  NaN   
2                          NaN                  NaN   
3                          NaN                  NaN   
4                          NaN                  NaN   
5                          NaN                  NaN   
...                        ...                  ...   
606                        NaN                  NaN   
607                        NaN                  NaN   
608                        NaN                  NaN   
609                        NaN                  NaN   
610                        NaN                  NaN   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                             NaN                              NaN   
2                             NaN                              NaN   
3                             NaN                              NaN   
4                             NaN                              NaN   
5                             NaN                              NaN   
...                           ...                              ...   
606                           NaN                              NaN   
607                           NaN                              NaN   
608                           NaN                              NaN   
609                           NaN                              NaN   
610                           NaN                              NaN   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                      NaN                   NaN                          NaN   
2                      NaN                   NaN                          NaN   
3                      NaN                   NaN                          NaN   
4                      NaN                   NaN                          NaN   
5                      NaN                   NaN                          NaN   
...                    ...                   ...                          ...   
606                    NaN                   NaN                          NaN   
607                    NaN                   NaN                          NaN   
608                    NaN                   NaN                          NaN   
609                    NaN                   NaN                          NaN   
610                    NaN                   NaN                          3.5   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                                  NaN  ...          NaN           NaN   
2                                  NaN  ...          NaN           NaN   
3                                  NaN  ...          NaN           NaN   
4                                  NaN  ...          NaN           NaN   
5                                  NaN  ...          Na

# 4. Perform User-based Collaborative Filtering

### 4.1 Fill the missing values with the average ratings

Use User-base collaborative filtering

In [44]:
user_utility_matrix = ratings_matrix.copy()
user_utility_matrix = user_utility_matrix.apply(lambda row: row.fillna(row.mean()), axis=1)
user_utility_matrix

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1         4.366379                                 4.366379   
2         3.948276                                 3.948276   
3         2.435897                                 2.435897   
4         3.555556                                 3.555556   
5         3.636364                                 3.636364   
...            ...                                      ...   
606       3.657399                                 3.657399   
607       3.786096                                 3.786096   
608       3.134176                                 3.134176   
609       3.270270                                 3.270270   
610       4.000000                                 3.688556   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                     4.366379             4.366379   
2                     3.948276             3.948276   
3                     2.435897             2.435897   
4                     3.555556             3.555556   
5                     3.636364             3.636364   
...                        ...                  ...   
606                   3.657399             3.657399   
607                   3.786096             3.786096   
608                   3.134176             3.134176   
609                   3.270270             3.270270   
610                   3.688556             3.688556   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                        4.366379                         4.366379   
2                        3.948276                         3.948276   
3                        2.435897                         2.435897   
4                        3.555556                         3.555556   
5                        3.636364                         3.636364   
...                           ...                              ...   
606                      3.657399                         3.657399   
607                      3.786096                         3.786096   
608                      3.134176                         3.134176   
609                      3.270270                         3.270270   
610                      3.688556                         3.688556   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                 4.366379              4.366379                     4.366379   
2                 3.948276              3.948276                     3.948276   
3                 2.435897              2.435897                     2.435897   
4                 3.555556              3.555556                     3.555556   
5                 3.636364              3.636364                     3.636364   
...                    ...                   ...                          ...   
606               3.657399              3.657399                     3.657399   
607               3.786096              3.786096                     3.786096   
608               3.134176              3.134176                     3.134176   
609               3.270270              3.270270                     3.270270   
610               3.688556              3.688556                     3.500000   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                             4.366379  ...     4.366379      4.366379   
2                             3.948276  ...     3.948276      3.948276   
3                             2.435897  ...     2.435897      2.435897   
4                             3.555556  ...     3.555556      3.555556   
5                             3.636364  ...     3.63636

# 4.2 Choose the correlation of all users with User 1 only

We need to transpose the matrix in order to capture the Users information (the rows)

In [45]:
user_corr_matrix =  user_utility_matrix.T.corr()
user_corr_matrix

userId       1             2             3         4         5         6    \
userId                                                                       
1       1.000000  1.264516e-03  5.525772e-04  0.048419  0.021847 -0.045497   
2       0.001265  1.000000e+00 -4.975816e-17 -0.017164  0.021796 -0.021051   
3       0.000553 -4.975816e-17  1.000000e+00 -0.011260 -0.031539  0.004800   
4       0.048419 -1.716402e-02 -1.125978e-02  1.000000 -0.029620  0.013956   
5       0.021847  2.179571e-02 -3.153892e-02 -0.029620  1.000000  0.009111   
...          ...           ...           ...       ...       ...       ...   
606     0.012016  6.225827e-03 -3.728895e-02  0.020590  0.026319 -0.009137   
607     0.055261 -2.050374e-02 -7.789105e-03  0.014628  0.031896  0.045501   
608     0.075224 -6.000828e-03 -1.300064e-02 -0.037569 -0.001751  0.021727   
609    -0.025713 -6.009100e-02 -1.168878e-16 -0.017884  0.093829  0.053017   
610     0.010932  2.499921e-02  1.954996e-02 -0.000995 -0.000278  0.009603   

userId           7         8             9             10   ...       601  \
userId                                                      ...             
1      -6.199672e-03  0.047013  1.950985e-02 -8.754088e-03  ...  0.018127   
2      -1.111357e-02 -0.048085  7.652805e-16  3.011629e-03  ... -0.050551   
3      -2.587070e-16 -0.032471 -4.812885e-16  3.774064e-16  ... -0.004904   
4       5.809139e-02  0.002065 -5.873603e-03  5.159032e-02  ... -0.037687   
5       1.011715e-02 -0.012284  7.750436e-16 -3.316512e-02  ...  0.015964   
...              ...       ...           ...           ...  ...       ...   
606     2.832591e-02  0.022277  3.163273e-02 -3.994577e-02  ...  0.053683   
607     3.098070e-02  0.048822 -1.216061e-02 -1.765576e-02  ...  0.049059   
608     2.841409e-02  0.071759  3.278284e-02 -5.199963e-02  ...  0.069198   
609     8.754391e-03  0.077180 -2.489604e-16 -4.009050e-02  ...  0.043465   
610     6.842957e-02  0.017144  5.189754e-02 -2.600368e-02  ...  0.021603   

userId       602       603           604           605       606       607  \
userId                                                                       
1      -0.017172 -0.015221 -3.705875e-02 -2.912138e-02  0.012016  0.055261   
2      -0.031581 -0.001688 -1.265569e-15 -6.430371e-16  0.006226 -0.020504   
3      -0.016117  0.017749 -8.106536e-16 -1.430628e-03 -0.037289 -0.007789   
4       0.063122  0.027640 -1.378212e-02  4.003747e-02  0.020590  0.014628   
5       0.012427  0.027076  1.246135e-02 -3.627206e-02  0.026319  0.031896   
...          ...       ...           ...           ...       ...       ...   
606     0.016384  0.098011  6.107833e-02  1.967830e-02  1.000000  0.017927   
607     0.038197  0.049317  2.355180e-03 -2.938114e-02  0.017927  1.000000   
608     0.051388  0.012801  6.318649e-03 -7.977761e-03  0.056676  0.044514   
609     0.062400  0.015334  9.403771e-02 -5.472183e-02  0.038422  0.019049   
610     0.030061  0.051255  1.562147e-02  6.983700e-02  0.075464  0.021860   

userId       608           609       610  
userId                                    
1       0.075224 -2.571255e-02  0.010932  
2      -0.006001 -6.009100e-02  0.024999  
3      -0.013001 -1.168878e-16  0.019550  
4      -0.037569 -1.788358e-02 -0.000995  
5      -0.001751  9.382892e-02 -0.000278  
...          ...           ...       ...  
606     0.056676  3.842210e-02  0.075464  
607     0.044514  1.904919e-02  0.021860  
608     1.000000  5.071449e-02  0.054454  
609     0.050714  1.000000e+00 -0.012471  
610     0.054454 -1.247143e-02  1.000000  

[610 rows x 610 columns]

In [46]:
corr_user_1 = user_corr_matrix.iloc[0]

In [47]:
corr_user_1.sort_values(ascending=False, inplace=True)
corr_user_1

userId
1      1.000000
301    0.124799
597    0.102631
414    0.101348
477    0.099217
         ...   
71    -0.082932
370   -0.086678
501   -0.090018
579   -0.105003
53          NaN
Name: 1, Length: 610, dtype: float64

The closest users are: 301 and 597 and 414

In [48]:
top50_users = corr_user_1[1:51]
top50_users

userId
301    0.124799
597    0.102631
414    0.101348
477    0.099217
57     0.099070
369    0.098295
206    0.096852
535    0.096493
590    0.095191
418    0.094153
120    0.092770
75     0.091987
577    0.089396
198    0.088883
160    0.088133
226    0.088068
266    0.086064
312    0.086017
19     0.085249
135    0.084672
484    0.084350
469    0.084184
72     0.083613
593    0.082403
44     0.081400
297    0.080839
434    0.078361
483    0.078085
449    0.077631
552    0.077630
171    0.077241
199    0.076905
45     0.076489
608    0.075224
494    0.073544
116    0.073329
450    0.072014
201    0.071913
387    0.071418
173    0.071317
600    0.069528
513    0.069213
524    0.069208
368    0.069179
555    0.068507
180    0.067516
445    0.067329
20     0.066990
307    0.066782
480    0.066395
Name: 1, dtype: float64

# 4.6 Predict the rating that User 1 might give for the movie with movieId 32 based on the top 50 user correlation matrix

{Hint: Predicted rating = sum of [(weights) * (ratings)] / sum of (weights )}.
Here, weights are the correlation of the corresponding user with the first user.). 
That is, the predicted rating is calculated as the weighted average of k similar users


In [49]:
# Calculate Predicted rating = sum of [(weights) * (ratings)] / sum of (weights )

In [50]:
sum_similarity = 0
weighted_ratings = 0

for user in top50_users.index:
    sum_user = df_combined[(df_combined['userId'] == user) & (df_combined['movieId'] == 32)]['rating'].sum()
    weighted_ratings += top50_users.loc[user] * sum_user
    sum_similarity += top50_users.loc[user]
    
print(weighted_ratings / sum_similarity)

2.4539691031029425


Downside of this approach: Everytime a user rates a movie, you have to go back and do all the calculations.


This can become very computational intensive

Item-based Collaborative filtering is a more recent approach to overcome this limitations

# 5. Perform Item-based Collaborative Filtering

### 5.1 Fill the column-wise NaN's in the User-Item Matrix with the corresponding movie's mean ratings, and find Pearson correlation between movies

Tell which items are similar (instead of users)

In [51]:
item_utility_matrix = ratings_matrix.copy()
item_utility_matrix = item_utility_matrix.apply(lambda col: col.fillna(col.mean()), axis=0)
item_utility_matrix

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              4.0                                      4.0   
2              4.0                                      4.0   
3              4.0                                      4.0   
4              4.0                                      4.0   
5              4.0                                      4.0   
...            ...                                      ...   
606            4.0                                      4.0   
607            4.0                                      4.0   
608            4.0                                      4.0   
609            4.0                                      4.0   
610            4.0                                      4.0   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                          3.5                  5.0   
2                          3.5                  5.0   
3                          3.5                  5.0   
4                          3.5                  5.0   
5                          3.5                  5.0   
...                        ...                  ...   
606                        3.5                  5.0   
607                        3.5                  5.0   
608                        3.5                  5.0   
609                        3.5                  5.0   
610                        3.5                  5.0   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                             4.0                              1.5   
2                             4.0                              1.5   
3                             4.0                              1.5   
4                             4.0                              1.5   
5                             4.0                              1.5   
...                           ...                              ...   
606                           4.0                              1.5   
607                           4.0                              1.5   
608                           4.0                              1.5   
609                           4.0                              1.5   
610                           4.0                              1.5   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                 3.176471                   3.0                     3.666667   
2                 3.176471                   3.0                     3.666667   
3                 3.176471                   3.0                     3.666667   
4                 3.176471                   3.0                     3.666667   
5                 3.176471                   3.0                     3.666667   
...                    ...                   ...                          ...   
606               3.176471                   3.0                     3.666667   
607               3.176471                   3.0                     3.666667   
608               3.176471                   3.0                     3.666667   
609               3.176471                   3.0                     3.666667   
610               3.176471                   3.0                     3.500000   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                             3.285714  ...          1.5        4.0625   
2                             3.285714  ...          1.5        4.0625   
3                             3.285714  ...          1.5        4.0625   
4                             3.285714  ...          1.5        4.0625   
5                             3.285714  ...          1.

• Choose the correlation of all movies with the movie Jurassic Park (1993) only.
• Sort the  Jurassic Park movie correlation in descending order
• Drop the NaN values generated in the correlation matrix
• Find the most 10 movies similar to the movie Jurassic Park (1993)

In [54]:
item_corr_matrix = item_utility_matrix.corr()
item_corr_matrix

title                                      '71 (2014)  \
title                                                   
'71 (2014)                                        NaN   
'Hellboy': The Seeds of Creation (2004)           NaN   
'Round Midnight (1986)                            NaN   
'Salem's Lot (2004)                               NaN   
'Til There Was You (1997)                         NaN   
...                                               ...   
eXistenZ (1999)                                   NaN   
xXx (2002)                                        NaN   
xXx: State of the Union (2005)                    NaN   
¡Three Amigos! (1986)                             NaN   
À nous la liberté (Freedom for Us) (1931)         NaN   

title                                      'Hellboy': The Seeds of Creation (2004)  \
title                                                                                
'71 (2014)                                                                     NaN   
'Hellboy': The Seeds of Creation (2004)                                        NaN   
'Round Midnight (1986)                                                         NaN   
'Salem's Lot (2004)                                                            NaN   
'Til There Was You (1997)                                                      NaN   
...                                                                            ...   
eXistenZ (1999)                                                                NaN   
xXx (2002)                                                                     NaN   
xXx: State of the Union (2005)                                                 NaN   
¡Three Amigos! (1986)                                                          NaN   
À nous la liberté (Freedom for Us) (1931)                                      NaN   

title                                      'Round Midnight (1986)  \
title                                                               
'71 (2014)                                                    NaN   
'Hellboy': The Seeds of Creation (2004)                       NaN   
'Round Midnight (1986)                                        NaN   
'Salem's Lot (2004)                                           NaN   
'Til There Was You (1997)                                     NaN   
...                                                           ...   
eXistenZ (1999)                                               NaN   
xXx (2002)                                                    NaN   
xXx: State of the Union (2005)                                NaN   
¡Three Amigos! (1986)                                         NaN   
À nous la liberté (Freedom for Us) (1931)                     NaN   

title                                      'Salem's Lot (2004)  \
title                                                            
'71 (2014)                                                 NaN   
'Hellboy': The Seeds of Creation (2004)                    NaN   
'Round Midnight (1986)                                     NaN   
'Salem's Lot (2004)                                        NaN   
'Til There Was You (1997)                                  NaN   
...                                                        ...   
eXistenZ (1999)                                            NaN   
xXx (2002)                                                 NaN   
xXx: State of the Union (2005)                             NaN   
¡Three Amigos! (1986)                                      NaN   
À nous la liberté (Freedom for Us) (1931)                  NaN   

title                                      'Til There Was You (1997)  \
title                                                                  
'71 (2014)                                                       NaN   
'Hellboy': The Seeds of Creation (2004)                          NaN   
'Round Midnight (1986)                                           NaN   
'Salem's Lot (2004)   

In [55]:
item_corr_matrix.dropna(inplace=True)
item_corr_matrix

Empty DataFrame
Columns: ['71 (2014), 'Hellboy': The Seeds of Creation (2004), 'Round Midnight (1986), 'Salem's Lot (2004), 'Til There Was You (1997), 'Tis the Season for Love (2015), 'burbs, The (1989), 'night Mother (1986), (500) Days of Summer (2009), *batteries not included (1987), ...All the Marbles (1981), ...And Justice for All (1979), 00 Schneider - Jagd auf Nihil Baxter (1994), 1-900 (06) (1994), 10 (1979), 10 Cent Pistol (2015), 10 Cloverfield Lane (2016), 10 Items or Less (2006), 10 Things I Hate About You (1999), 10 Years (2011), 10,000 BC (2008), 100 Girls (2000), 100 Streets (2016), 101 Dalmatians (1996), 101 Dalmatians (One Hundred and One Dalmatians) (1961), 101 Dalmatians II: Patch's London Adventure (2003), 101 Reykjavik (101 Reykjavík) (2000), 102 Dalmatians (2000), 10th & Wolf (2006), 10th Kingdom, The (2000), 10th Victim, The (La decima vittima) (1965), 11'09"01 - September 11 (2002), 11:14 (2003), 11th Hour, The (2007), 12 Angry Men (1957), 12 Angry Men (1997), 12 Chairs (1971), 12 Chairs (1976), 12 Rounds (2009), 12 Years a Slave (2013), 127 Hours (2010), 13 Assassins (Jûsan-nin no shikaku) (2010), 13 Ghosts (1960), 13 Going on 30 (2004), 13 Hours (2016), 13 Sins (2014), 13 Tzameti (2005), 13th (2016), 13th Warrior, The (1999), 1408 (2007), 1492: Conquest of Paradise (1992), 15 Minutes (2001), 16 Blocks (2006), 17 Again (2009), 1776 (1972), 18 Again! (1988), 187 (One Eight Seven) (1997), 1900 (Novecento) (1976), 1941 (1979), 1969 (1988), 1984 (Nineteen Eighty-Four) (1984), 2 Days in New York (2012), 2 Days in Paris (2007), 2 Days in the Valley (1996), 2 Fast 2 Furious (Fast and the Furious 2, The) (2003), 2 Guns (2013), 20 Dates (1998), 20 Feet from Stardom (Twenty Feet from Stardom) (2013), 20 Million Miles to Earth (1957), 20,000 Days on Earth (2014), 20,000 Leagues Under the Sea (1916), 20,000 Leagues Under the Sea (1954), 200 Cigarettes (1999), 2001 Maniacs (2005), 2001: A Space Odyssey (1968), 2010: The Year We Make Contact (1984), 2012 (2009), 2046 (2004), 2048: Nowhere to Run (2017), 21 (2008), 21 Grams (2003), 21 Jump Street (2012), 21 Up (1977), 21 and Over (2013), 22 Jump Street (2014), 24 Hour Party People (2002), 25th Hour (2002), 27 Dresses (2008), 28 Days (2000), 28 Days Later (2002), 28 Up (1985), 28 Weeks Later (2007), 3 Days to Kill (2014), 3 Extremes (Three... Extremes) (Saam gaang yi) (2004), 3 Idiots (2009), 3 Ninjas (1992), 3 Ninjas Kick Back (1994), 3 Ninjas Knuckle Up (1995), 3 Ninjas: High Noon On Mega Mountain (1998), 3 Women (Three Women) (1977), ...]
Index: []

[0 rows x 9719 columns]

### 5.2 Choose the correlation of all movies with the movie Jurassic Park (1993) only.

In [ ]:
similar_movies = item_corr_matrix[['Jurassic Park (1993)']].sort_values(ascending=False, by='Jurassic Park (1993)')

In [ ]:
top10_items = similar_movies[1:11]
print('top10 similar movies: ', top10_items)

Above methos are considered Memory-based approaches (non-machine learning).

### Now we move to Machine Learning approaches

# 6. Perform KNNBasic, SVD, NMF Model-based Collaborative Filtering

    Initialize KNNBasic with similarity configuration as Mean Squared Distance Similarity 
(msd), 20 neighbors and cross-validate 5 folds against measure RMSE.
    (Hint: cross_validate(algo=algo, data=data, measures=['RMSE'], cv=5, verbose=True)) 

    Initialize Singular Value Decomposition (SVD) and cross-validate 5 folds against measure RMSE.

    Initialize Non-Negative Matrix Factorization (NMF)and cross-validate 5 folds against measure RMSE.

    Print best score and best params from Cross Validate on all the models built.


In [57]:
from surprise import Reader, Dataset, KNNBasic, SVD, NMF
from surprise.model_selection import GridSearchCV, cross_validate

In [58]:
# Range of the rating values
reader = Reader(rating_scale=(0.5, 5.0))

data = Dataset.load_from_df(ratings[['userId','movieId','rating']], reader=reader)

In [59]:
data

In [60]:
sim_options = {'name': 'msd'}

algo = KNNBasic(k=20, sim_options=sim_options)
# Do 5 traingin rounds (folds)
cross_validate(algo=algo, data=data, measures=['RMSE'], cv=5, verbose=True)

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Evaluating RMSE of algorithm KNNBasic on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9379  0.9459  0.9389  0.9437  0.9404  0.9414  0.0030  
Fit time          0.11    0.11    0.11    0.11    0.10    0.11    0.00    
Test time         0.91    0.93    0.85    0.95    0.87    0.90    0.04    


{'test_rmse': array([0.93791723, 0.94592346, 0.9389041 , 0.94367568, 0.94041006]),
 'fit_time': (0.11356592178344727,
  0.11406898498535156,
  0.10692524909973145,
  0.1095728874206543,
  0.10492229461669922),
 'test_time': (0.9058220386505127,
  0.9324102401733398,
  0.8524909019470215,
  0.948538064956665,
  0.8739676475524902)}

### Initialize Singular Value Decomposition (SVD) and cross-validate 5 folds against measure RMSE.

In [61]:
algo = SVD()
cross_validate(algo=algo,data=data, measures=['RMSE'],cv=5,verbose=True)

Evaluating RMSE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.8766  0.8747  0.8789  0.8644  0.8742  0.8738  0.0050  
Fit time          0.89    0.90    0.90    0.89    0.90    0.90    0.00    
Test time         0.18    0.09    0.18    0.10    0.18    0.14    0.04    


{'test_rmse': array([0.87655849, 0.87466827, 0.87894974, 0.86443508, 0.87424936]),
 'fit_time': (0.8928639888763428,
  0.9021098613739014,
  0.8974971771240234,
  0.8916959762573242,
  0.8981719017028809),
 'test_time': (0.18135714530944824,
  0.09290909767150879,
  0.17759490013122559,
  0.09571981430053711,
  0.17620205879211426)}

In [63]:
param_grid = {'n_factors': [50, 75], 'lr_all':[0.5, 0.05], 'reg_all': [0.06, 0.04]}

#Use grid search for parameter tuning
#SVD model was imported from surprise library
gs = GridSearchCV(algo_class=SVD, measures=['RMSE'], param_grid=param_grid)
gs.fit(data)

In [64]:
print("Best score", gs.best_score['rmse'])
print("Best parameters", gs.best_params['rmse'])

Best score 0.8640547994678828
Best parameters {'n_factors': 75, 'lr_all': 0.05, 'reg_all': 0.06}


### Initialize Non-Negative Matrix Factorization (NMF)and cross-validate 5 folds against measure RMSE.

In [65]:
algo = NMF()
cross_validate(data=data, algo=algo, measures=['RMSE'], cv=5, verbose=True)

Evaluating RMSE of algorithm NMF on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9216  0.9305  0.9189  0.9197  0.9235  0.9228  0.0041  
Fit time          2.08    2.02    2.08    2.05    2.05    2.05    0.02    
Test time         0.07    0.07    0.07    0.08    0.07    0.07    0.00    


{'test_rmse': array([0.92156034, 0.93048505, 0.91889842, 0.91973279, 0.9235445 ]),
 'fit_time': (2.0760090351104736,
  2.0192439556121826,
  2.0757079124450684,
  2.0460309982299805,
  2.047574043273926),
 'test_time': (0.07261967658996582,
  0.07241082191467285,
  0.07339787483215332,
  0.07767295837402344,
  0.07421588897705078)}

# Make model predictions to recommend movies to the users

In [66]:
from surprise.model_selection import train_test_split

In [67]:
train_data, test_data = train_test_split(data, test_size=0.25)

model = algo.fit(train_data)

predictions = model.test(test_data)

predictions
# get the RMSE to test predictions

[Prediction(uid=514, iid=1961, r_ui=4.0, est=4.088954640431975, details={'was_impossible': False}),
 Prediction(uid=166, iid=1721, r_ui=3.0, est=3.88522125539548, details={'was_impossible': False}),
 Prediction(uid=597, iid=5060, r_ui=5.0, est=4.2634187227556595, details={'was_impossible': False}),
 Prediction(uid=600, iid=185, r_ui=2.5, est=2.4793208289545943, details={'was_impossible': False}),
 Prediction(uid=339, iid=1101, r_ui=2.5, est=3.4189582676902903, details={'was_impossible': False}),
 Prediction(uid=474, iid=27882, r_ui=4.0, est=3.9260277422330057, details={'was_impossible': False}),
 Prediction(uid=257, iid=420, r_ui=4.0, est=2.528155510594905, details={'was_impossible': False}),
 Prediction(uid=606, iid=2183, r_ui=4.5, est=3.262001126326928, details={'was_impossible': False}),
 Prediction(uid=254, iid=47, r_ui=4.5, est=4.24236463353022, details={'was_impossible': False}),
 Prediction(uid=68, iid=5219, r_ui=4.0, est=2.976131577642092, details={'was_impossible': False}),
 P

for the first prediction, the real value is 4.0 (r_ui) and the estimation is 4.08 (est)

This are the predictions of the model for what rating users might give to the movies

If we want to predict for a user, we would need to pick a user and insert it in the model.test_data
Then you can sort the 'est' values, filter out the movies that the user has already seen, and pick the iid of the top 10 'est' values. Assuming that the user may rate those movies the highest (assuming he will like this movies)